name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Rsync updated code to EC2
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ ec2-user@15.185.175.159:/home/ec2-user/Petrolube-Whatsapp-Bot

      - name: Install & Restart app
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@15.185.175.159 << 'EOF'
            cd /home/ec2-user/Petrolube-Whatsapp-Bot
            npm install
      - name: Upload .env to EC2
        run: |
          echo "${{ secrets.APP_ENV_FILE }}" | ssh -o StrictHostKeyChecking=no ec2-user@15.185.175.159 "cat > /home/ec2-user/Petrolube-Whatsapp-Bot/.env"

            pm2 restart MechanicBot || pm2 start MechanicBot.js --name MechanicBot
            
          EOF
